### ISSUE TITLE
How to get holography

### ISSUE THREAD

**Issue by shy-29** [THUHoloLab/pixel-super-resolution-phase-retrieval#4]
Hello, what is the relationship between the phase in the code and the hologram, how can I use a picture to get a hologram, and after loading this hologram on the SLM, the image can be reconstructed

**Comment by Yunhui-Gao** [comment]
Hi there. In this project we focus on holographic imaging, that is how we can recover the amplitude and phase of the unknown object based on the diffraction patterns. We don't necessarily need an SLM in our configuration. The phase in the code corresponds to the phase of the unknown object we try to recover. For more details, you may refer to our paper: https://doi.org/10.1364/OE.434449. If you are interested in holographic display (or computer generated holography, CGH), this is beyond the scope of this project. Nevertheless, I think the hologram synthesis and reconstruction problems have something in common.

**Comment by shy-29** [comment]
OK,Thanks
